Graphics.prototype.setFontOpenSans = function(scale) {
    // Actual height 66 (70 - 5)
    g.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAA/8AAAAAAAAAAAAA/8AAAAAAAAAAAAB/+AAAAAAAAAAAAB/+AAAAAAAAAAAAB/+AAAAAAAAAAAAB/+AAAAAAAAAAAAB/+AAAAAAAAAAAAA/+AAAAAAAAAAAAA/8AAAAAAAAAAAAAf4AAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAcAAAAAAAAAAAAAD8AAAAAAAAAAAAAf8AAAAAAAAAAAAB/8AAAAAAAAAAAAP/8AAAAAAAAAAAB//8AAAAAAAAAAAH//8AAAAAAAAAAA///8AAAAAAAAAAH///wAAAAAAAAAAf//+AAAAAAAAAAD///4AAAAAAAAAAf///AAAAAAAAAAB///4AAAAAAAAAAP///gAAAAAAAAAB///8AAAAAAAAAAH///gAAAAAAAAAA///+AAAAAAAAAAH///wAAAAAAAAAAf//+AAAAAAAAAAD///4AAAAAAAAAAf///AAAAAAAAAAB///4AAAAAAAAAAP///gAAAAAAAAAA///8AAAAAAAAAAA///gAAAAAAAAAAA//+AAAAAAAAAAAA//wAAAAAAAAAAAA/+AAAAAAAAAAAAA/4AAAAAAAAAAAAA/AAAAAAAAAAAAAA4AAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAH/////AAAAAAAAA//////4AAAAAAAD///////AAAAAAAP///////wAAAAAA////////4AAAAAB////////+AAAAAD/////////AAAAAH///8A////gAAAAP//AAAAD//wAAAAf/wAAAAAP/wAAAAf/AAAAAAD/4AAAA/8AAAAAAA/4AAAA/4AAAAAAAf8AAAA/wAAAAAAAP8AAAB/gAAAAAAAH+AAAB/gAAAAAAAH+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/AAAAAAAAD+AAAB/gAAAAAAAH+AAAB/gAAAAAAAH+AAAA/wAAAAAAAP8AAAA/4AAAAAAAf8AAAA/8AAAAAAA/8AAAAf/AAAAAAD/4AAAAP/wAAAAAP/4AAAAP//AAAAD//wAAAAH///4Af///gAAAAD/////////AAAAAB////////+AAAAAAf///////8AAAAAAP///////wAAAAAAD///////AAAAAAAA//////8AAAAAAAAD/////gAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAB8AAAAAAAAAAAAAB+AAAAAAAAAAAAAD/AAAAAAAAAAAAAH/AAAAAAAAAAAAAP+AAAAAAAAAAAAAP+AAAAAAAAAAAAAf8AAAAAAAAAAAAA/4AAAAAAAAAAAAB/wAAAAAAAAAAAAB/wAAAAAAAAAAAAD/gAAAAAAAAAAAAH/AAAAAAAAAAAAAP+AAAAAAAAAAAAAP8AAAAAAAAAAAAAf8AAAAAAAAAAAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAwAAAAAAAP8AAAAB4AAAAAAAf8AAAAD8AAAAAAA/8AAAAH+AAAAAAB/8AAAAH+AAAAAAD/8AAAAP+AAAAAAH/8AAAAP8AAAAAAP/8AAAAf8AAAAAAf/8AAAAf4AAAAAA//8AAAA/wAAAAAB//8AAAA/wAAAAAD/38AAAA/gAAAAAH/n8AAAB/gAAAAAP/H8AAAB/gAAAAAf+H8AAAB/AAAAAA/8H8AAAB/AAAAAB/4H8AAAB/AAAAAD/wH8AAAB/AAAAAH/gH8AAAB/AAAAAP/AH8AAAB/AAAAAf+AH8AAAB/AAAAA/8AH8AAAB/AAAAB/4AH8AAAB/AAAAD/wAH8AAAB/AAAAP/gAH8AAAB/AAAAf/AAH8AAAB/gAAA/+AAH8AAAB/wAAB/8AAH8AAAA/wAAH/4AAH8AAAA/4AAf/wAAH8AAAA/+AB//gAAH8AAAAf/wf//AAAH8AAAAf////+AAAH8AAAAP////4AAAH8AAAAH////wAAAH8AAAAD////gAAAH8AAAAB///+AAAAH8AAAAA///8AAAAH8AAAAAf//wAAAAH8AAAAAD/+AAAAAH8AAAAAAPAAAAAAH8AAAAAAAAAAAAAH8AAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAABgAAAAAAAfwAAAAD4AAAAAAAf4AAAAH8AAAAAAAP4AAAAH+AAAAAAAP8AAAAP+AAAAAAAP8AAAAP8AAAAAAAH8AAAAf4AAAAAAAH8AAAAf4AAAAAAAH+AAAAfwAAAAAAAH+AAAA/wAAH8AAAD+AAAA/gAAH8AAAD+AAAA/gAAH8AAAD+AAAB/gAAH8AAAD+AAAB/AAAH8AAAD+AAAB/AAAH8AAAD+AAAB/AAAH8AAAD+AAAB/AAAH8AAAD+AAAB/AAAH8AAAD+AAAB/AAAH8AAAD+AAAB/AAAH+AAAD+AAAB/AAAH+AAAD+AAAB/AAAH+AAAD+AAAB/AAAH+AAAD+AAAB/AAAP+AAAD+AAAB/AAAP+AAAD+AAAB/AAAf/AAAH+AAAB/gAAf/AAAH8AAAB/gAA//AAAH8AAAA/wAB/fgAAP8AAAA/4AD/fwAAf8AAAA/+AP+fwAA/4AAAAf///+f8AB/4AAAAf///8P+AH/wAAAAP///8P////wAAAAH///4H////gAAAAH///wH////AAAAAD///gD////AAAAAA///AB///+AAAAAAf/+AB///8AAAAAAD/wAAf//wAAAAAAAAAAAP//AAAAAAAAAAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAD/gAAAAAAAAAAAAH/gAAAAAAAAAAAAP/gAAAAAAAAAAAA//gAAAAAAAAAAAB//gAAAAAAAAAAAH//gAAAAAAAAAAAP//gAAAAAAAAAAAf//gAAAAAAAAAAB/+/gAAAAAAAAAAD/8/gAAAAAAAAAAP/w/gAAAAAAAAAAf/g/gAAAAAAAAAA/+A/gAAAAAAAAAD/8A/gAAAAAAAAAH/4A/gAAAAAAAAAf/gA/gAAAAAAAAA//AA/gAAAAAAAAB/8AA/gAAAAAAAAH/4AA/gAAAAAAAAP/wAA/gAAAAAAAA//AAA/gAAAAAAAB/+AAA/gAAAAAAAD/4AAA/gAAAAAAAP/wAAA/gAAAAAAAf/gAAA/gAAAAAAB/+AAAA/gAAAAAAD/8AAAA/gAAAAAAH/wAAAA/gAAAAAAf/gAAAA/gAAAAAA/+AAAAA/gAAAAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAA//////////8AAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAfwAAAAAAA//gAAAf4AAAAA////wAAAP4AAAA/////wAAAP8AAAA/////4AAAP8AAAA/////4AAAH8AAAA/////4AAAH8AAAA/////wAAAH+AAAA/////wAAAH+AAAA///wfwAAAD+AAAA/wAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAD+AAAA/gAAfwAAAH+AAAA/gAAf4AAAH8AAAA/gAAf4AAAP8AAAA/gAAP8AAAP8AAAA/gAAP8AAAf8AAAA/gAAP+AAA/4AAAA/gAAH/AAB/4AAAA/gAAH/wAH/wAAAA/gAAH/+Af/wAAAA/gAAD/////gAAAA/gAAB/////AAAAA/gAAA////+AAAAA/gAAA////8AAAAAAAAAAf///4AAAAAAAAAAH///wAAAAAAAAAAD///AAAAAAAAAAAA//8AAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//4AAAAAAAAAAH////gAAAAAAAAB/////8AAAAAAAAH//////AAAAAAAA///////wAAAAAAB///////4AAAAAAH///////+AAAAAAP////////AAAAAAf////////gAAAAA//+B/wA//gAAAAB//gD/AAH/wAAAAD/8AH+AAD/4AAAAH/wAH8AAA/4AAAAH/gAP4AAAf8AAAAP/AAPwAAAP8AAAAP8AAfwAAAH8AAAAf4AAfgAAAH+AAAAf4AA/gAAAD+AAAA/wAA/gAAAD+AAAA/gAA/AAAAD+AAAA/gAA/AAAAD+AAAB/gAA/AAAAD+AAAB/AAA/AAAAD+AAAB/AAA/AAAAD+AAAB/AAA/AAAAD+AAAB/AAA/AAAAD+AAAB/AAA/gAAAD+AAAB+AAA/gAAAH+AAAB+AAA/gAAAH+AAAB+AAA/wAAAP8AAAB+AAAf4AAAf8AAAB+AAAf8AAA/8AAAB/AAAf+AAB/4AAAB/AAAP/gAH/4AAAB/AAAP/////wAAAB/AAAH/////gAAAB/AAAD/////AAAAB/AAAD////+AAAAAAAAAB////8AAAAAAAAAAf///4AAAAAAAAAAP///gAAAAAAAAAAD//+AAAAAAAAAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAAAAAA/gAAAAAAAAEAAAA/gAAAAAAAAcAAAA/gAAAAAAAD8AAAA/gAAAAAAAP8AAAA/gAAAAAAA/8AAAA/gAAAAAAD/8AAAA/gAAAAAAP/8AAAA/gAAAAAB//8AAAA/gAAAAAH//8AAAA/gAAAAAf//4AAAA/gAAAAB///gAAAA/gAAAAH//+AAAAA/gAAAAf//4AAAAA/gAAAD///gAAAAA/gAAAP//8AAAAAA/gAAA///wAAAAAA/gAAD///AAAAAAA/gAAP//8AAAAAAA/gAA///gAAAAAAA/gAH//+AAAAAAAA/gAf//4AAAAAAAA/gB///gAAAAAAAA/gH//8AAAAAAAAA/gf//wAAAAAAAAA/h///AAAAAAAAAA/v//8AAAAAAAAAA////wAAAAAAAAAA///+AAAAAAAAAAA///4AAAAAAAAAAA///gAAAAAAAAAAA//+AAAAAAAAAAAA//wAAAAAAAAAAAA//AAAAAAAAAAAAA/8AAAAAAAAAAAAA/wAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAAAAAAD//wAAAAAAH/gAAH//8AAAAAAf/8AAf//+AAAAAA//+AA////AAAAAD///gB////gAAAAH///wD////wAAAAH///4D////wAAAAP///4H/4H/4AAAAf///8P/AB/4AAAAf/B/+P+AAf8AAAA/8AP/f8AAP8AAAA/4AH/f4AAH8AAAA/wAD//wAAH+AAAB/gAB//gAAD+AAAB/AAA//AAAD+AAAB/AAA//AAAD+AAAB/AAAf+AAAD+AAAB/AAAf+AAAB+AAAB+AAAP8AAAB+AAAB+AAAP8AAAB+AAAB+AAAH8AAAB+AAAB+AAAP+AAAB+AAAB+AAAP+AAAB+AAAB/AAAf/AAAB+AAAB/AAAf/AAAD+AAAB/AAA//gAAD+AAAB/AAA//gAAD+AAAB/gAB//wAAD+AAAA/wAD//wAAH8AAAA/4AH+f4AAP8AAAA/8Af+f8AAP8AAAAf/j/8P+AA/4AAAAf///4P/gB/4AAAAP///4H/4P/wAAAAH///wD////wAAAAH///gB////gAAAAD///AB////AAAAAB//+AA////AAAAAAf/4AAf//+AAAAAAH/gAAH//4AAAAAAAAAAAD//wAAAAAAAAAAAA/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/4AAAAAAAAAAAB///AAAAAAAAAAAH///wAAAAAAAAAAf///4AAAAAAAAAA////+AAAD8AAAAB/////AAAD+AAAAD/////AAAD+AAAAH/////gAAD+AAAAP/////wAAD+AAAAf/wAH/wAAD+AAAAf+AAB/4AAD+AAAA/8AAA/4AAB+AAAA/4AAAf4AAB+AAAA/wAAAP8AAB+AAAB/gAAAH8AAB+AAAB/gAAAH8AAB+AAAB/AAAAH8AAD+AAAB/AAAAD8AAD+AAAB/AAAAD8AAD+AAAB/AAAAD8AAD+AAAB/AAAAD8AAD+AAAB/AAAAD8AAH+AAAB/AAAAD8AAH8AAAB/AAAAD8AAH8AAAB/AAAAH8AAP8AAAB/AAAAH8AAf4AAAB/gAAAH4AAf4AAAA/gAAAP4AA/wAAAA/wAAAPwAD/wAAAA/4AAAfwAH/gAAAAf8AAA/gAP/gAAAAf/AAB/AA//AAAAAP/gAD/AH/+AAAAAH/8AP+B//8AAAAAH////////4AAAAAD////////wAAAAAB////////gAAAAAAf//////+AAAAAAAP//////8AAAAAAAD//////gAAAAAAAA/////+AAAAAAAAAP////wAAAAAAAAAA///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAADAAAAAAAB/gAAAAf4AAAAAAD/wAAAA/8AAAAAAH/wAAAA/+AAAAAAH/4AAAB/+AAAAAAH/4AAAB/+AAAAAAH/4AAAB/+AAAAAAH/4AAAB/+AAAAAAH/4AAAB/+AAAAAAD/wAAAA/8AAAAAAD/wAAAA/8AAAAAAB/AAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), 46, atob("GCEzMzMzMzMzMzMzGA=="), 90+(scale<<8)+(1<<16));
  }
  
  require("FontTeletext10x18Ascii").add(Graphics);
  
  var drawTimeout;
  
  const weekday = new Array(7);
  weekday[0] = "Sun";
  weekday[1] = "Mon";
  weekday[2] = "Tue";
  weekday[3] = "Wed";
  weekday[4] = "Thu";
  weekday[5] = "Fri";
  weekday[6] = "Sat";
  
  function queueDraw() {
    if(drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = setTimeout(()=> {
      drawTimeout = undefined;
      draw();
    },60000 - (Date.now() % 60000));
  }
  
  function draw() {
    var x = g.getWidth()/2;
    var y = g.getHeight()/2;
    g.reset();
    var date = new Date();
    var h = date.getHours(), m=date.getMinutes();
    var timeStr = require("locale").time(date,3);
    
    // draw hour
    g.setFontAlign(0,0).setFont("OpenSans");
    g.clearRect(0,y-55,g.getWidth(),g.getHeight());
    g.drawString(("0"+h).substr(-2),x-15,y-20);
    g.drawString(("0"+m).substr(-2),x-15,y+55);
    
    var mon = date.getMonth(), day = weekday[date.getDay()], mon_day=date.getDate();
    
    g.setFontAlign(0,0).setFont("Teletext10x18Ascii");
    g.drawString(day,x+60,y-20);
    g.drawString(mon_day,x+60,y+10);
    g.drawString(mon+1,x+60,y+30);
    
      
  
    
    queueDraw();
  }
  
  g.clear();
  draw();
  
  Bangle.setUI("clock");
  Bangle.loadWidgets();
  Bangle.drawWidgets();